const allcountries = [
  { id: "AF", name: "Afghanistan", capital: "Kaboul", flag: "https://flagcdn.com/af.svg" },
  { id: "AL", name: "Albanie", capital: "Tirana", flag: "https://flagcdn.com/al.svg" },
  { id: "DZ", name: "Algérie", capital: "Alger", flag: "https://flagcdn.com/dz.svg" },
  { id: "AD", name: "Andorre", capital: "Andorre-la-Vieille", flag: "https://flagcdn.com/ad.svg" },
  { id: "AO", name: "Angola", capital: "Luanda", flag: "https://flagcdn.com/ao.svg" },
  { id: "AG", name: "Antigua et Barbuda", capital: "Saint John's", flag: "https://flagcdn.com/ag.svg" },
  { id: "AR", name: "Argentina", capital: "Buenos Aires", flag: "https://flagcdn.com/ar.svg" },
  { id: "AM", name: "Arménie", capital: "Erevan", flag: "https://flagcdn.com/am.svg" },
  { id: "AU", name: "Australie", capital: "Canberra", flag: "https://flagcdn.com/au.svg" },
  { id: "AT", name: "Austriche", capital: "Vienne", flag: "https://flagcdn.com/at.svg" },
  { id: "AZ", name: "Azerbaïdjan", capital: "Bakou", flag: "https://flagcdn.com/az.svg" },
  { id: "BS", name: "Bahamas", capital: "Nassau", flag: "https://flagcdn.com/bs.svg" },
  { id: "BH", name: "Bahraïn", capital: "Manama", flag: "https://flagcdn.com/bh.svg" },
  { id: "BD", name: "Bangladesh", capital: "Dacca", flag: "https://flagcdn.com/bd.svg" },
  { id: "BB", name: "Barbades", capital: "Bridgetown", flag: "https://flagcdn.com/bb.svg" },
  { id: "BY", name: "Belarus", capital: "Minsk", flag: "https://flagcdn.com/by.svg" },
  { id: "BE", name: "Belgique", capital: "Bruxelles", flag: "https://flagcdn.com/be.svg" },
  { id: "BZ", name: "Belize", capital: "Belmopan", flag: "https://flagcdn.com/bz.svg" },
  { id: "BJ", name: "Benin", capital: "Porto-Novo", flag: "https://flagcdn.com/bj.svg" },
  { id: "BT", name: "Bhoutan", capital: "Thimphou", flag: "https://flagcdn.com/bt.svg" },
  { id: "BO", name: "Bolivie", capital: "Sucre", flag: "https://flagcdn.com/bo.svg" },
  { id: "BA", name: "Bosnie Herzégovine", capital: "Sarajevo", flag: "https://flagcdn.com/ba.svg" },
  { id: "BW", name: "Botswana", capital: "Gaborone", flag: "https://flagcdn.com/bw.svg" },
  { id: "BR", name: "Brésil", capital: "Brasilia", flag: "https://flagcdn.com/br.svg" },
  { id: "BN", name: "Brunei", capital: "Bandar Seri Begawan", flag: "https://flagcdn.com/bn.svg" },
  { id: "BG", name: "Bulgarie", capital: "Sofia", flag: "https://flagcdn.com/bg.svg" },
  { id: "BF", name: "Burkina Faso", capital: "Ouagadougou", flag: "https://flagcdn.com/bf.svg" },
  { id: "BI", name: "Burundi", capital: "Gitega", flag: "https://flagcdn.com/bi.svg" },
  { id: "CV", name: "Cabo Verde", capital: "Praia", flag: "https://flagcdn.com/cv.svg" },
  { id: "KH", name: "Cambodia", capital: "Phnom Penh", flag: "https://flagcdn.com/kh.svg" },
  { id: "CM", name: "Cameroon", capital: "Yaoundé", flag: "https://flagcdn.com/cm.svg" },
  { id: "CA", name: "Canada", capital: "Ottawa", flag: "https://flagcdn.com/ca.svg" },
  { id: "CF", name: "Centrafrique", capital: "Bangui", flag: "https://flagcdn.com/cf.svg" },
  { id: "TD", name: "Tchad", capital: "N'Djamena", flag: "https://flagcdn.com/td.svg" },
  { id: "CL", name: "Chili", capital: "Santiago", flag: "https://flagcdn.com/cl.svg" },
  { id: "CN", name: "Chine", capital: "Pékin", flag: "https://flagcdn.com/cn.svg" },
  { id: "CO", name: "Colombie", capital: "Bogota", flag: "https://flagcdn.com/co.svg" },
  { id: "KM", name: "Comores", capital: "Moroni", flag: "https://flagcdn.com/km.svg" },
  { id: "CG", name: "Congo", capital: "Brazzaville", flag: "https://flagcdn.com/cg.svg" },
  { id: "CD", name: "République démocratique du Congo", capital: "Kinshasa", flag: "https://flagcdn.com/cd.svg" },
  { id: "CR", name: "Costa Rica", capital: "San José", flag: "https://flagcdn.com/cr.svg" },
  { id: "HR", name: "Croatia", capital: "Zagreb", flag: "https://flagcdn.com/hr.svg" },
  { id: "CU", name: "Cuba", capital: "La Havane", flag: "https://flagcdn.com/cu.svg" },
  { id: "CY", name: "Chypre", capital: "Nicosie", flag: "https://flagcdn.com/cy.svg" },
  { id: "CZ", name: "Tchéquie", capital: "Prague", flag: "https://flagcdn.com/cz.svg" },
  { id: "DK", name: "Danemark", capital: "Copenhagen", flag: "https://flagcdn.com/dk.svg" },
  { id: "DJ", name: "Djibouti", capital: "Djibouti", flag: "https://flagcdn.com/dj.svg" },
  { id: "DM", name: "Dominique", capital: "Roseau", flag: "https://flagcdn.com/dm.svg" },
  { id: "DO", name: "République Dominicaine", capital: "Saint-Domingue", flag: "https://flagcdn.com/do.svg" },
  { id: "EC", name: "Équateur", capital: "Quito", flag: "https://flagcdn.com/ec.svg" },
  { id: "EG", name: "Égypte", capital: "Cairo", flag: "https://flagcdn.com/eg.svg" },
  { id: "SV", name: "Salvador", capital: "San Salvador", flag: "https://flagcdn.com/sv.svg" },
  { id: "GQ", name: "Guinée Équatoriale", capital: "Malabo", flag: "https://flagcdn.com/gq.svg" },
  { id: "ER", name: "Érythrée", capital: "Asmara", flag: "https://flagcdn.com/er.svg" },
  { id: "EE", name: "Estonie", capital: "Tallinn", flag: "https://flagcdn.com/ee.svg" },
  { id: "SZ", name: "Eswatini", capital: "Mbabane", flag: "https://flagcdn.com/sz.svg" },
  { id: "ET", name: "Ethiopie", capital: "Addis Abeba", flag: "https://flagcdn.com/et.svg" },
  { id: "FJ", name: "Fidji", capital: "Suva", flag: "https://flagcdn.com/fj.svg" },
  { id: "FI", name: "Finlande", capital: "Helsinki", flag: "https://flagcdn.com/fi.svg" },
  { id: "FR", name: "France", capital: "Paris", flag: "https://flagcdn.com/fr.svg" },
  { id: "GA", name: "Gabon", capital: "Libreville", flag: "https://flagcdn.com/ga.svg" },
  { id: "GM", name: "Gambie", capital: "Banjul", flag: "https://flagcdn.com/gm.svg" },
  { id: "GE", name: "Georgie", capital: "Tbilisi", flag: "https://flagcdn.com/ge.svg" },
  { id: "DE", name: "Allemagne", capital: "Berlin", flag: "https://flagcdn.com/de.svg" },
  { id: "GH", name: "Ghana", capital: "Accra", flag: "https://flagcdn.com/gh.svg" },
  { id: "GR", name: "Grèce", capital: "Athènes", flag: "https://flagcdn.com/gr.svg" },
  { id: "GD", name: "Grenade", capital: "Saint George's", flag: "https://flagcdn.com/gd.svg" },
  { id: "GT", name: "Guatemala", capital: "Guatemala", flag: "https://flagcdn.com/gt.svg" },
  { id: "GN", name: "Guinée", capital: "Conakry", flag: "https://flagcdn.com/gn.svg" },
  { id: "GW", name: "Guinée-Bissau", capital: "Bissau", flag: "https://flagcdn.com/gw.svg" },
  { id: "GY", name: "Guyana", capital: "Georgetown", flag: "https://flagcdn.com/gy.svg" },
  { id: "HT", name: "Haiti", capital: "Port-au-Prince", flag: "https://flagcdn.com/ht.svg" },
  { id: "HN", name: "Honduras", capital: "Tegucigalpa", flag: "https://flagcdn.com/hn.svg" },
  { id: "HU", name: "Hongrie", capital: "Budapest", flag: "https://flagcdn.com/hu.svg" },
  { id: "IS", name: "Islande", capital: "Reykjavik", flag: "https://flagcdn.com/is.svg" },
  { id: "IN", name: "Inde", capital: "New Delhi", flag: "https://flagcdn.com/in.svg" },
  { id: "ID", name: "Indonésie", capital: "Jakarta/Lusantara", flag: "https://flagcdn.com/id.svg" },
  { id: "IR", name: "Iran", capital: "Téhéran", flag: "https://flagcdn.com/ir.svg" },
  { id: "IQ", name: "Irak", capital: "Baghdad", flag: "https://flagcdn.com/iq.svg" },
  { id: "IE", name: "Irlande", capital: "Dublin", flag: "https://flagcdn.com/ie.svg" },
  { id: "IL", name: "Israël", capital: "Jerusalem", flag: "https://flagcdn.com/il.svg" },
  { id: "IT", name: "Italie", capital: "Rome", flag: "https://flagcdn.com/it.svg" },
  { id: "JM", name: "Jamaïque", capital: "Kingston", flag: "https://flagcdn.com/jm.svg" },
  { id: "JP", name: "Japon", capital: "Tokyo", flag: "https://flagcdn.com/jp.svg" },
  { id: "JO", name: "Jordanie", capital: "Amman", flag: "https://flagcdn.com/jo.svg" },
  { id: "KZ", name: "Kazakhstan", capital: "Astana", flag: "https://flagcdn.com/kz.svg" },
  { id: "KE", name: "Kenya", capital: "Nairobi", flag: "https://flagcdn.com/ke.svg" },
  { id: "KI", name: "Kiribati", capital: "Tarawa", flag: "https://flagcdn.com/ki.svg" },
  { id: "KW", name: "Koweït", capital: "Koweït", flag: "https://flagcdn.com/kw.svg" },
  { id: "KG", name: "Kirghizistan", capital: "Bishkek", flag: "https://flagcdn.com/kg.svg" },
  { id: "LA", name: "Laos", capital: "Vientiane", flag: "https://flagcdn.com/la.svg" },
  { id: "LV", name: "Lettonie", capital: "Riga", flag: "https://flagcdn.com/lv.svg" },
  { id: "LB", name: "Liban", capital: "Beyrouth", flag: "https://flagcdn.com/lb.svg" },
  { id: "LS", name: "Lesotho", capital: "Maseru", flag: "https://flagcdn.com/ls.svg" },
  { id: "LR", name: "Liberia", capital: "Monrovia", flag: "https://flagcdn.com/lr.svg" },
  { id: "LY", name: "Libye", capital: "Tripoli", flag: "https://flagcdn.com/ly.svg" },
  { id: "LI", name: "Liechtenstein", capital: "Vaduz", flag: "https://flagcdn.com/li.svg" },
  { id: "LT", name: "Lithuanie", capital: "Vilnius", flag: "https://flagcdn.com/lt.svg" },
  { id: "LU", name: "Luxembourg", capital: "Luxembourg", flag: "https://flagcdn.com/lu.svg" },
  { id: "MG", name: "Madagascar", capital: "Antananarivo", flag: "https://flagcdn.com/mg.svg" },
  { id: "MW", name: "Malawi", capital: "Lilongwe", flag: "https://flagcdn.com/mw.svg" },
  { id: "MY", name: "Malaysie", capital: "Kuala Lumpur", flag: "https://flagcdn.com/my.svg" },
  { id: "MV", name: "Maldives", capital: "Malé", flag: "https://flagcdn.com/mv.svg" },
  { id: "ML", name: "Mali", capital: "Bamako", flag: "https://flagcdn.com/ml.svg" },
  { id: "MT", name: "Malte", capital: "La Vallette", flag: "https://flagcdn.com/mt.svg" },
  { id: "MH", name: "Iles Marshall", capital: "Majuro", flag: "https://flagcdn.com/mh.svg" },
  { id: "MR", name: "Mauritanie", capital: "Nouakchott", flag: "https://flagcdn.com/mr.svg" },
  { id: "MU", name: "Maurice", capital: "Port Louis", flag: "https://flagcdn.com/mu.svg" },
  { id: "MX", name: "Mexique", capital: "Mexico", flag: "https://flagcdn.com/mx.svg" },
  { id: "FM", name: "Micronesie", capital: "Palikir", flag: "https://flagcdn.com/fm.svg" },
  { id: "MD", name: "Moldavie", capital: "Chisinau", flag: "https://flagcdn.com/md.svg" },
  { id: "MC", name: "Monaco", capital: "Monaco", flag: "https://flagcdn.com/mc.svg" },
  { id: "MN", name: "Mongolie", capital: "Oulan-bator", flag: "https://flagcdn.com/mn.svg" },
  { id: "ME", name: "Monténégro", capital: "Podgorica", flag: "https://flagcdn.com/me.svg" },
  { id: "MA", name: "Maroc", capital: "Rabat", flag: "https://flagcdn.com/ma.svg" },
  { id: "MZ", name: "Mozambique", capital: "Maputo", flag: "https://flagcdn.com/mz.svg" },
  { id: "MM", name: "Myanmar", capital: "Naypyidaw", flag: "https://flagcdn.com/mm.svg" },
  { id: "NA", name: "Namibie", capital: "Windhoek", flag: "https://flagcdn.com/na.svg" },
  { id: "NR", name: "Nauru", capital: "Yaren", flag: "https://flagcdn.com/nr.svg" },
  { id: "NP", name: "Népal", capital: "Katmandou", flag: "https://flagcdn.com/np.svg" },
  { id: "NL", name: "Pays-bas", capital: "Amsterdam", flag: "https://flagcdn.com/nl.svg" },
  { id: "NZ", name: "Nouvelle Zélande", capital: "Wellington", flag: "https://flagcdn.com/nz.svg" },
  { id: "NI", name: "Nicaragua", capital: "Managua", flag: "https://flagcdn.com/ni.svg" },
  { id: "NE", name: "Niger", capital: "Niamey", flag: "https://flagcdn.com/ne.svg" },
  { id: "NG", name: "Nigeria", capital: "Abuja", flag: "https://flagcdn.com/ng.svg" },
  { id: "KP", name: "Corée du nord", capital: "Pyongyang", flag: "https://flagcdn.com/kp.svg" },
  { id: "MK", name: "Macédoine du nord", capital: "Skopje", flag: "https://flagcdn.com/mk.svg" },
  { id: "NO", name: "Norvège", capital: "Oslo", flag: "https://flagcdn.com/no.svg" },
  { id: "OM", name: "Oman", capital: "Mascate", flag: "https://flagcdn.com/om.svg" },
  { id: "PK", name: "Pakistan", capital: "Islamabad", flag: "https://flagcdn.com/pk.svg" },
  { id: "PW", name: "Palaos", capital: "Ngerulmud", flag: "https://flagcdn.com/pw.svg" },
  { id: "PS", name: "Palestine", capital: "Jérusalem est", flag: "https://flagcdn.com/ps.svg" },
  { id: "PA", name: "Panama", capital: "Panama", flag: "https://flagcdn.com/pa.svg" },
  { id: "PG", name: "Papouasie nouvelle guinée", capital: "Port Moresby", flag: "https://flagcdn.com/pg.svg" },
  { id: "PY", name: "Paraguay", capital: "Asuncion", flag: "https://flagcdn.com/py.svg" },
  { id: "PE", name: "Pérou", capital: "Lima", flag: "https://flagcdn.com/pe.svg" },
  { id: "PH", name: "Philippines", capital: "Manille", flag: "https://flagcdn.com/ph.svg" },
  { id: "PL", name: "Pologne", capital: "Varsovie", flag: "https://flagcdn.com/pl.svg" },
  { id: "PT", name: "Portugal", capital: "Lisbonne", flag: "https://flagcdn.com/pt.svg" },
  { id: "QA", name: "Qatar", capital: "Doha", flag: "https://flagcdn.com/qa.svg" },
  { id: "RO", name: "Romanie", capital: "Bucarest", flag: "https://flagcdn.com/ro.svg" },
  { id: "RU", name: "Russie", capital: "Moscou", flag: "https://flagcdn.com/ru.svg" },
  { id: "RW", name: "Rwanda", capital: "Kigali", flag: "https://flagcdn.com/rw.svg" },
  { id: "KN", name: "Saint Kitts and Nevis", capital: "Basseterre", flag: "https://flagcdn.com/kn.svg" },
  { id: "LC", name: "Sainte Lucie", capital: "Castries", flag: "https://flagcdn.com/lc.svg" },
  { id: "VC", name: "Saint Vincent et les Grenadines", capital: "Kingstown", flag: "https://flagcdn.com/vc.svg" },
  { id: "WS", name: "Samoa", capital: "Apia", flag: "https://flagcdn.com/ws.svg" },
  { id: "SM", name: "Saint Marin", capital: "Saint Marin", flag: "https://flagcdn.com/sm.svg" },
  { id: "ST", name: "Sao Tomé et Principe", capital: "Sao Tomé", flag: "https://flagcdn.com/st.svg" },
  { id: "SA", name: "Arabie saoudite", capital: "Riyad", flag: "https://flagcdn.com/sa.svg" },
  { id: "SN", name: "Sénégal", capital: "Dakar", flag: "https://flagcdn.com/sn.svg" },
  { id: "RS", name: "Serbie", capital: "Belgrade", flag: "https://flagcdn.com/rs.svg" },
  { id: "SC", name: "Seychelles", capital: "Victoria", flag: "https://flagcdn.com/sc.svg" },
  { id: "SL", name: "Sierra Leone", capital: "Freetown", flag: "https://flagcdn.com/sl.svg" },
  { id: "SG", name: "Singapour", capital: "Singapour", flag: "https://flagcdn.com/sg.svg" },
  { id: "SK", name: "Slovaquie", capital: "Bratislava", flag: "https://flagcdn.com/sk.svg" },
  { id: "SI", name: "Slovénie", capital: "Ljubljana", flag: "https://flagcdn.com/si.svg" },
  { id: "SB", name: "Iles Salomon", capital: "Honiara", flag: "https://flagcdn.com/sb.svg" },
  { id: "SO", name: "Somalie", capital: "Mogadiscio", flag: "https://flagcdn.com/so.svg" },
  { id: "ZA", name: "Afrique du sud", capital: "Pretoria", flag: "https://flagcdn.com/za.svg" },
  { id: "KR", name: "SCorée du sud", capital: "Séoul", flag: "https://flagcdn.com/kr.svg" },
  { id: "SS", name: "Soudan du sud", capital: "Djouba", flag: "https://flagcdn.com/ss.svg" },
  { id: "ES", name: "Espagne", capital: "Madrid", flag: "https://flagcdn.com/es.svg" },
  { id: "LK", name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", flag: "https://flagcdn.com/lk.svg" },
  { id: "SD", name: "Soudan", capital: "Khartoum", flag: "https://flagcdn.com/sd.svg" },
  { id: "SR", name: "Suriname", capital: "Paramaribo", flag: "https://flagcdn.com/sr.svg" },
  { id: "SE", name: "Suède", capital: "Stockholm", flag: "https://flagcdn.com/se.svg" },
  { id: "CH", name: "Suisse", capital: "Berne", flag: "https://flagcdn.com/ch.svg" },
  { id: "SY", name: "Syrie", capital: "Damas", flag: "https://flagcdn.com/sy.svg" },
  { id: "TJ", name: "Tadjikistan", capital: "Douchanbé", flag: "https://flagcdn.com/tj.svg" },
  { id: "TZ", name: "Tanzanie", capital: "Dodoma", flag: "https://flagcdn.com/tz.svg" },
  { id: "TH", name: "Thaïlande", capital: "Bangkok", flag: "https://flagcdn.com/th.svg" },
  { id: "TL", name: "Timor oriental", capital: "Dili", flag: "https://flagcdn.com/tl.svg" },
  { id: "TG", name: "Togo", capital: "Lomé", flag: "https://flagcdn.com/tg.svg" },
  { id: "TO", name: "Tonga", capital: "Nukuʻalofa", flag: "https://flagcdn.com/to.svg" },
  { id: "TT", name: "Trinité et Tobago", capital: "Port d'Espagne", flag: "https://flagcdn.com/tt.svg" },
  { id: "TN", name: "Tunisie", capital: "Tunis", flag: "https://flagcdn.com/tn.svg" },
  { id: "TR", name: "Turquie", capital: "Ankara", flag: "https://flagcdn.com/tr.svg" },
  { id: "TM", name: "Turkménistan", capital: "Ashgabat", flag: "https://flagcdn.com/tm.svg" },
  { id: "TV", name: "Tuvalu", capital: "Funafuti", flag: "https://flagcdn.com/tv.svg" },
  { id: "UG", name: "Ouganda", capital: "Kampala", flag: "https://flagcdn.com/ug.svg" },
  { id: "UA", name: "Ukraine", capital: "Kiev", flag: "https://flagcdn.com/ua.svg" },
  { id: "AE", name: "EAU", capital: "Abu Dhabi", flag: "https://flagcdn.com/ae.svg" },
  { id: "GB", name: "Royaume uni", capital: "Londres", flag: "https://flagcdn.com/gb.svg" },
  { id: "US", name: "États-Unis", capital: "Washington", flag: "https://flagcdn.com/us.svg" },
  { id: "UY", name: "Uruguay", capital: "Montevideo", flag: "https://flagcdn.com/uy.svg" },
  { id: "UZ", name: "Ouzbékistan", capital: "Tashkent", flag: "https://flagcdn.com/uz.svg" },
  { id: "VU", name: "Vanuatu", capital: "Port Vila", flag: "https://flagcdn.com/vu.svg" },
  { id: "VA", name: "Vatican", capital: "Vatican", flag: "https://flagcdn.com/va.svg" },
  { id: "VE", name: "Vénézuela", capital: "Caracas", flag: "https://flagcdn.com/ve.svg" },
  { id: "VN", name: "Vietnam", capital: "Hanoi", flag: "https://flagcdn.com/vn.svg" },
  { id: "YE", name: "Yemen", capital: "Sanaa", flag: "https://flagcdn.com/ye.svg" },
  { id: "ZM", name: "Zambie", capital: "Lusaka", flag: "https://flagcdn.com/zm.svg" },
  { id: "ZW", name: "Zimbabwe", capital: "Harare", flag: "https://flagcdn.com/zw.svg" },
];